name: shell commands

on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: echo"welcome to development"
      - name: multiline script
        run: |
         node -v
         npm -v
      - name: Python command
        run: |
         python -c "import platform; print(platform.processor())"
        shell: python
jobs:
  run-shell-command:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
        shell: pwsh  # Use PowerShell Core shell

      - name: Directory Bash
        run: pwd
        shell: bash
