name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to windows-latest or macos-latest as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script (default on Ubuntu)
        run: |
          echo "Running Bash commands"
          pwd
        shell: bash

      - name: Run PowerShell script (Windows only)
        runs-on: windows-latest
        shell: pwsh
        run: |
          echo "Running PowerShell commands"
          Get-Location

      - name: Run Command Prompt script (Windows only)
        runs-on: windows-latest
        shell: cmd
        run: |
          echo "Running Command Prompt commands"
          cd

      - name: Run Python script (using Bash on Ubuntu/macOS)
        run: |
          python -c "import platform; print(platform.processor())"
        shell: bash

      - name: Run a script with specific shell (macOS example)
        runs-on: macos-latest
        shell: zsh
        run: |
          echo "Running Zsh commands"
          pwd
