name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # The runner environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script (default on Ubuntu)
        run: |
          echo "Running Bash commands"
          pwd
        shell: bash

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        shell: bash

      - name: Run Python script (using Bash on Ubuntu/macOS)
        run: |
          python -c "import platform; print(platform.processor())"
        shell: bash
